### Tensor
텐서(Tensor)는 파이토치의 기본 단위이며 GPU 연산을 가능하게 한다. 또한 Numpy의 배열과 유사하여 손쉽게 다룰 수 있다.

1. 텐서 만들기

PyTorch에서 모델 학습과 연산은 모두 텐서 기반으로 수행하기 때문에 torch.Tensor 객체로 변환해 주어야 한다.
* 예를 들어, 리스트나 넘파이 배열은 연산/미분이 불가능하기 때문에, 텐서 객체로 변환해야 한다.
* 이렇게 변환한 tensor는 .to('cuda') 등을 사용해서 GPU에서 빠르게 연산 가능하다.
  * 하지만 cuda는 NVIDIA GPU에서만 작동하고, 맥북은 NVIDIA GPU를 사용하지 않기 때문에 .to('cuda') 사용이 불가하다.

* 내 노트북인 **M2 Pro**인 경우 일반 NVIDIA GPU가 아닌 Metal backend인 MPS(Metal Performance Shader = Apple GPU)으르 가지고 있기 때문에 'cuda' 사용이 불가하다.
  * 일반 설치 방법인 `pip install torch`가 아닌, Metal을 지원하는 [PyTorch nightly](https://pytorch.org/get-started/locally/#macos-arm64) 버전을 설치해줘야 한다. `conda install pytorch torchvision torchaudio -c pytorch-nightly`
  * 그리고 코드가 MPS로 돌아가게 하기 위해서 아래의 코드를 추가해 줘야 한다.
    ```
    device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
    tensor = torch.tensor([1.0, 2.0, 3.0]).to(device)
    ```
  * 하지만 아직 모든 Pytorch 기능이 MPS에서 100% 지원되는 것은 아니다. Google Colab(무료 GPU)이나 AWS도 좋은 선택이다.

In [16]:
%pip install torch
%pip install numpy

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [17]:
import torch # Pytorch를 사용하기 위한 기본 라이브러리이다.
import numpy as np

In [18]:
# 빈 텐서 생성
x = torch.empty(5, 4) # 5x4 행렬 생성
print(x) # 초기화되지 않은 행렬인 경우 해당 시점에 할당된 메모리에 존재하던 값들이 초기값으로 나타난다.

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [19]:
torch.ones(3, 3) # 3x3 행렬을 생성하고 모든 원소를 1로 초기화한다.

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [20]:
torch.zeros(3, 3) # 3x3 행렬을 생성하고 모든 원소를 0으로 초기화한다.

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
torch.rand(5, 6) # 5x6 행렬을 생성하고 모든 원소를 랜덤한 값으로 초기화한다.

tensor([[0.5913, 0.8495, 0.2228, 0.4009, 0.1759, 0.5141],
        [0.6833, 0.9884, 0.2234, 0.6081, 0.1964, 0.8496],
        [0.0548, 0.5911, 0.4214, 0.7609, 0.0557, 0.4055],
        [0.9672, 0.6127, 0.0771, 0.6036, 0.2049, 0.7959],
        [0.3616, 0.1079, 0.9352, 0.0878, 0.8146, 0.4359]])

2. 리스트, 넘파이 배열을 텐서로 만들기

In [22]:
l = [13, 4] # 리스트 생성
r = np.array([4, 56, 7]) # 넘파이 배열 생성

In [23]:
torch.tensor(l) # 리스트를 텐서로 변환

tensor([13,  4])

In [24]:
torch.tensor(r) # 넘파이 배열을 텐서로 변환

tensor([ 4, 56,  7])

In [ ]:
torch.FloatTensor(r) # 실수형 텐서로 변환

tensor([ 4., 56.,  7.])

3. 텐서의 크기와 타입 확인하기

In [30]:
x.size() # 텐서의 크기를 확인하는 방법
# x.size()[1] # 4

torch.Size([5, 4])

In [27]:
type(x)

torch.Tensor

4. 텐서의 덧셈

In [32]:
x = torch.rand(2, 2) # 2x2
y = torch.rand(2, 2) # 2x2
print(x)
print(y)

tensor([[0.9133, 0.8487],
        [0.0217, 0.5941]])
tensor([[0.0250, 0.2033],
        [0.4985, 0.6887]])


In [33]:
x + y # 텐서의 덧셈

tensor([[0.9383, 1.0520],
        [0.5202, 1.2828]])

In [34]:
torch.add(x, y) # torch.add()를 사용한 덧셈

tensor([[0.9383, 1.0520],
        [0.5202, 1.2828]])

In [36]:
y.add(x) # 두 텐서의 합의 또 다른 표현이지만 이는 y에 x를 더한다는 의미다.

tensor([[0.9383, 1.0520],
        [0.5202, 1.2828]])

In [ ]:
print("원래 y: ", y)
y.add_(x) # y에 x를 더한 후 y에 저장한다.

print("y=y+x: ", y) # y.add_는 y에 x를 더한 값을 y에 대체한다. (inplace 방식)

원래 y:  tensor([[0.0250, 0.2033],
        [0.4985, 0.6887]])
y=y+x:  tensor([[0.9383, 1.0520],
        [0.5202, 1.2828]])


5. 텐서의 크기 변환하기

In [38]:
x = torch.rand(8, 8) # 8x8
print(x.size()) 

torch.Size([8, 8])


In [39]:
a = x.view(64) # 크기를 바꿔주는 view 8*8(행렬) -> 64(1차원 벡터)
print(a.size()) 

torch.Size([64])


In [ ]:
# -1은 원래 크기가 되게 하는 값
# 원래는 -1 위치에 4가 들어가는게 맞는데 -1을 넣으면 자동으로 계산되어 4가 들어가게 된다. -1은 한번 밖에 사용 못한다.
# 8x8(64) -> 4x4x4(64)
b = x.view(-1, 4, 4) 
print(b.size()) # 4x4x4

torch.Size([4, 4, 4])


6. 텐서에서 넘파이로 만들기

In [43]:
x = torch.rand(8, 8) 
y = x.numpy() # 넘파이 배열로 변환
print(y)

[[0.43252575 0.6920703  0.07739574 0.831251   0.0522148  0.37973505
  0.64793235 0.9531009 ]
 [0.03008229 0.92926294 0.11123085 0.93049246 0.76308113 0.9754637
  0.36660695 0.05856687]
 [0.775738   0.6983376  0.27533758 0.0358941  0.34590054 0.9921308
  0.08021611 0.56548035]
 [0.1393727  0.26979315 0.83859646 0.9046985  0.07144886 0.60760427
  0.26895726 0.7366213 ]
 [0.6463927  0.6224601  0.07077765 0.98919064 0.05555409 0.13882321
  0.08678496 0.00804847]
 [0.5090243  0.07360029 0.48290372 0.30433744 0.70840675 0.84893864
  0.962731   0.2626285 ]
 [0.99328846 0.49464917 0.26876724 0.50858337 0.1328283  0.747576
  0.4576792  0.31577492]
 [0.472506   0.7664223  0.4810465  0.65746343 0.85337037 0.3127823
  0.9761925  0.3446116 ]]


In [44]:
type(y)

numpy.ndarray

7. 단일 텐서에서 값으로 뽑아내기

In [53]:
loss = torch.ones(1) 

In [55]:
# print(loss) # 텐서 값이 그대로 출력된다.
print(loss.item()) # 텐서의 값을 가져오는 방법

1.0
